version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: idkwhyureadthis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: food-service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: